name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Build
      run: go build -v ./...

    - name: Test
      run: | 
       go test -coverprofile coverage.out ./...
       go tool cover -html=coverage.out -o coverage.html
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Coverage
        path: coverage.*
   
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
